[build]
  publish = "app/static"
  functions = "netlify/functions"

[dev]
  command = ""
  port = 8889
  publish = "app/static"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["elevenlabs"]
  node_bundler          = "esbuild"

[functions."interact"]
  timeout = 90

[functions."*"]
  runtime = "node" # Switched from Python to Node.js

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
